### ISSUE TITLE
Book 3.5.10 HDI deployment failed with exit code 1

### ISSUE THREAD

**Issue by mata-r** [krisho007/c_cpe_13_certification#1]
Failing to deploy to HANA

On page 119 code for entity definition
```
entity Statuses: CodeList{
key code: String(2)
}
```

the key field code is set to String length >> 2
but either it should be three or the data should be only two characters because it fails to deploy to HANA.

**Comment by mahesh0431** [comment]
HI @mata-r ,

Thanks for pointing this out!!. you are right, it should be String(3), which was updated in the subsequent chapters git repos. We will update the old ones soon.

Kind Regards,
Mahesh

**Comment by mata-r** [comment]
Apologies, I did not find anywhere else to send comments. I am just trying to provide information for other readers and avoid spending time on minor issues.
